use Mix.Config

# Configure your database
config :tumblrx, Tumblrx.Repo,
  database: "tumblrx_dev",
  username: "postgres",
  password: "",
  hostname: "localhost",
  # username: "tdzzsubsneivnb",
  # password: "78d324fb5d735f0c6c7d0e5f564608e4053de71a5e7be9e766ad5740a75f685d",
  # database: "dcmv6avbr6nlk9",
  # hostname: "ec2-54-243-239-199.compute-1.amazonaws.com",
  # ssl: true,
  # ssl_opts: [
  #   cacertfile: "priv/AmazonRootCA1.pem"
  # ],
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :tumblrx, TumblrxWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
